### PR TITLE
eigend test

### PR DESCRIPTION
**Pull request by talbotray**

### CODE REVIEW

**Comment by rec** [comment]
Well, this is exciting!  :-)

**Comment by TheTechnobear** [comment]
I’m a bit confused about this PR, it seems to be mainly commits from me ... why is someone pushing my changes upstream? 

If it’s changes based of my fork , it should really be pushed to my fork.  

The reason I’ve not been pushing upstream is I’m unable to release ( and no one else is releasing) from this repo - so pushing back to it only creates effort- it doesn’t achieve anything.

**Comment by TheTechnobear** [comment]
Also I’d need some details on changes.... as appears to be a single commit without any details of changes made.  


~~It looks like an import of latest juce~~
~~( which should always be done as a single commit , due to the number of files it changes.)~~
~~Combined with a few python changes?~~

**EDIT: after review, Ive realised, the JUCE and python changes were also changes Ive made, so there appears to be nothing new in this PR.**

Also has it been tested on all platforms ?

Let’s discuss best way forward.

**Comment by TheTechnobear** [comment]
ok, so Ive reviewed this PR.

as far as I can tell this PR **only** includes change that I have made - that are in my Fork
https://github.com/thetechnobear/EigenD

as mentioned above, I've good reasons for not pushing these up to the origin.
and I also believe, as they are my changes that I am the developer that should really decide if these changes up pushed up - since Im the one that actually know what the changes do ;) 

so Im **not** going to merge this PR, and simply close the PR.

to end users: 
all of this code is already in my repo (see above) and is already released, there was nothing new here - it may have even been pushed in error (given the title of PR is "eigend test") 

@talbotray - if you have changes you wish to make based off of my repo, please push to my repo.
also please give some details about what the changes are.

btw: for discussion about dev on eigend, Id recommend you post on:
[https://community.polyexpression.com/](https://community.polyexpression.com/)

its where I and other EigenD developers/users hang out.

**Pull request closed without merging**
